### ISSUE TITLE
Currently can not add intelligraph to exsisting project

### ISSUE THREAD

**Issue by jensschmeink** [dlr-gtlab/intelligraph-module#204] opened 2024-11-06 13:48 UTC

**Comment by rainman110** [comment] 2024-11-06 14:04
I recently experienced the same problem, but only on linux.

**Comment by jensschmeink** [comment] 2024-11-06 14:05
Seems to be related to the intelli folder in the project

**Comment by rainman110** [comment] 2024-11-06 14:18
I am wondering, whether this happens only with gtlab 2.1, as the package interface has changed and was adapted.

**Comment by mariusalexander** [comment] 2024-11-12 09:18
This is the same issue as described in #193 and it should already be fixed in the the main branch. Can you verify that you are not working on an outdated version?

**Comment by rainman110** [comment] 2024-11-12 12:42
It's definitely possible that I used an outdated version. The problem is now gone.

**Closed by rainman110** 2024-11-12 12:42 UTC
